let state={page:'dashboard',nickname:'',score:0,streak:0,maxStreak:0,index:0,current:null,questions:[],timer:null,remaining:15,positions:[]};
const $=s=>document.querySelector(s); const content=$('#content');
function clearTimer(){if(state.timer){clearInterval(state.timer);state.timer=null}}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderDashboard(){clearTimer();state.page='dashboard';content.innerHTML=`<div class="panel"><h1 class="title">MES 모니터링 현황</h1><div class="sub">실시간 생산·출고·품질 모니터링</div><div class="dashboard-grid"><div class="card"><h3>생산 현황</h3><div class="big">정상</div><div class="notice">생산 라인 정상 운영 중</div></div><div class="card"><h3>출고 현황</h3><div class="big">정상</div><div class="notice">출고 작업 정상 처리 중</div></div><div class="card"><h3>품질 현황</h3><div class="big">정상</div><div class="notice">품질 검사 정상 진행 중</div></div></div><div class="notice">※ 시스템 점검이 필요하면 '★ 두뇌 점검' 메뉴를 선택하십시오.</div></div>`}
function startQuiz(){clearTimer();state.page='quiz';state.nickname='';state.score=0;state.streak=0;state.maxStreak=0;state.index=0;content.innerHTML=`<div class="namebox"><h2>★ MES 두뇌 점검</h2><p class="sub">닉네임을 입력하고 시작하세요.</p><input id="nickname" maxlength="20" placeholder="닉네임"><button class="btn btn-primary" id="startBtn">두뇌 점검 시작</button></div>`;$('#startBtn').onclick=()=>{const n=$('#nickname').value.trim();if(!n){$('#nickname').focus();return}state.nickname=n;state.questions=[...QUESTIONS].sort(()=>Math.random()-.5);state.positions=state.questions.map((_,i)=>i%4).sort(()=>Math.random()-.5);nextQuestion()}}
function nextQuestion(){clearTimer();if(state.index>=state.questions.length){finishGame(false);return}const raw=state.questions[state.index];const correct=raw.options[raw.correct];const wrong=raw.options.filter((_,i)=>i!==raw.correct).sort(()=>Math.random()-.5);const opts=[...wrong];opts.splice(state.positions[state.index],0,correct);const ci=opts.indexOf(correct);state.current={q:raw.q,options:opts,correct:ci,explanation:raw.explanation};state.remaining=15;renderQuestion();state.timer=setInterval(()=>{state.remaining--;updateTimer();if(state.remaining<=0){clearTimer();answer(-1)}},1000)}
function renderQuestion(){const c=state.current;content.innerHTML=`<div class="quiz-card"><div class="quiz-top"><div class="meta">문제 ${state.index+1} / ${state.questions.length}　|　점수 ${state.score}　|　연속 ${state.streak}</div><div class="timer" id="timer">남은 시간 15초</div></div><div class="question">${escapeHtml(c.q)}</div><div class="answers">${c.options.map((o,i)=>`<button class="answer" data-i="${i}">${String.fromCharCode(9312+i)} ${escapeHtml(o)}</button>`).join('')}</div><div class="btnrow"><button class="btn btn-danger" id="giveup">그만하기</button></div></div>`;document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>answer(+b.dataset.i));$('#giveup').onclick=()=>finishGame(true)}
function updateTimer(){const t=$('#timer');if(t)t.textContent=`남은 시간 ${state.remaining}초`}
function answer(choice){clearTimer();const c=state.current;let title,msg;if(choice===c.correct){state.streak++;state.maxStreak=Math.max(state.maxStreak,state.streak);state.score++;title='정답입니다!';msg=`+1점　|　연속 정답 ${state.streak}회`}else{state.streak=0;title='오답입니다!';msg='아쉽네요. 아래에서 정답과 해설을 확인하세요.'}state.index++;content.innerHTML=`<div class="panel result"><h2>${title}</h2><div class="msg">${msg}</div><div class="answerbox"><div class="ans">정답 : ${escapeHtml(c.options[c.correct])}</div><div class="label">해설</div><div class="exp">${escapeHtml(c.explanation)}</div></div><div class="score">현재 점수 ${state.score}점</div><div class="combo">🔥 연속 정답 ${state.streak}회</div><div class="buttons"><button class="btn btn-danger" id="resultGiveup">그만하기</button><button class="btn btn-primary" id="next">다음 문제</button></div></div>`;$('#resultGiveup').onclick=()=>finishGame(true);$('#next').onclick=nextQuestion}
async function api(method,params={}){try{if(!SERVER_URL)return null;if(method==='GET'){const r=await fetch(SERVER_URL+'?action=ranking',{cache:'no-store'});return await r.json()}const body=new URLSearchParams({action:'score',nickname:state.nickname,score:String(state.score),combo:String(state.maxStreak)});const r=await fetch(SERVER_URL,{method:'POST',body});return await r.json()}catch(e){return null}}
async function finishGame(abandoned){clearTimer();const submitted=await api('POST');content.innerHTML=`<div class="panel result"><h2>${abandoned?'두뇌 점검 포기':'두뇌 점검 완료'}</h2><div class="msg">현재 점수로 랭킹 등록!</div><div class="score">${escapeHtml(state.nickname)}　|　최종 점수 ${state.score}점</div><div class="combo">최고 콤보 ${state.maxStreak}연속</div><div class="notice">${submitted&&submitted.ok?'✓ 온라인 랭킹 등록 완료':'⚠ 온라인 랭킹 서버에 연결하지 못했습니다.'}</div><div class="buttons"><button class="btn btn-primary" id="again">다시 하기</button><button class="btn btn-light" id="rank">🏆 랭킹 보기</button><button class="btn btn-light" id="home">모니터링 화면</button></div></div>`;$('#again').onclick=startQuiz;$('#rank').onclick=showRanking;$('#home').onclick=renderDashboard}
async function showRanking(){clearTimer();content.innerHTML=`<div><h1 class="title">🏆 MES 두뇌 점검 랭킹</h1><div class="sub">친구들과 공유되는 온라인 최고 기록</div><div class="ranking" id="ranking">불러오는 중...</div><div class="footerbtn"><button class="btn btn-light" id="refresh">↻ 랭킹 새로고침</button></div></div>`;const result=await api('GET');const box=$('#ranking');if(!result||!result.ok){box.innerHTML='<div class="error">랭킹 서버에 연결할 수 없습니다.</div>';return}let rows=result.ranking||[];box.innerHTML=`<div class="rank-head"><div>순위</div><div>닉네임</div><div>점수</div><div>최고 콤보</div></div>`+rows.map((r,i)=>`<div class="rank-row"><div>${i<3?['🥇','🥈','🥉'][i]:i+1}</div><div>${escapeHtml(r.nickname||'')}</div><div>${Number(r.score||0)}점</div><div>${Number(r.combo||0)}연속</div></div>`).join('')+(rows.length?'':'<div style="padding:35px;text-align:center">아직 등록된 기록이 없습니다.</div>');$('#refresh').onclick=showRanking}
document.querySelectorAll('aside button').forEach(b=>b.onclick=()=>({dashboard:renderDashboard,quiz:startQuiz,ranking:showRanking}[b.dataset.page])());renderDashboard();
